### ISSUE TITLE
Argument parsing has extra prefix

### ISSUE THREAD

**Issue by shaowi** [AY2223S2-CS2103-F10-2/tp#162]
### Description

After navigating to video layer, a find command was called. However, the arguments does not tally to user's input.

### Steps for reproducing
`nav /mod CS2040S /lec Week1`
`find Topic /mod ST2334`

### Expected result
` Topic /mod ST2334`

### Actual result
![image](https://user-images.githubusercontent.com/66897775/226241618-768e8584-d256-4f3c-811d-fa2c315de693.png)
` Topic /mod ST2334 /lect Week1`

### Other details
I removed the spacing between the lecture and video names. E.g. Week 1 -> Week1

### Error output
None

**Comment by jedidiahC** [comment]
Thank you for raising this! This will be addressed by #161 also.
