### ISSUE TITLE
Out of place white box at bottom right of output message box

### ISSUE THREAD

**Issue by hingen** [AY2223S2-CS2103-F10-2/tp#190]
### Description
White box at the bottom right of the output message box. It appears at the position where the horizontal and vertical scroll bars intercept.

### Steps for reproducing
Type a command that produces a long output message. For example, `add` which will print the usage message for the `add` command
Make sure the window is narrow enough such that the horizontal scroll bar appears.  

### Expected result
No white box.

### Actual result
There is a white box.

### Other details
![image](https://user-images.githubusercontent.com/31367001/228146769-32d61e30-9905-4e74-95e8-d4fc11809b46.png)

### Error output
None

**Comment by shaowi** [comment]
I noticed this issue only occurs when there is an overflow for row texts.
If we keep the limit of row texts within the frame, this will not happen.
Just like this:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/66897775/228149210-e3300b3e-86b0-442d-8b1e-2d7ff5f6bb2a.png">

**Comment by shaowi** [comment]
Im facing this as well for find command. We can keep the sentence within the frame limit as a temporary solution
