### ISSUE TITLE
[PE-D][Tester C] Module Name allows texts that are too long to be displayed

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-F10-2/tp#239]
See the picture model names that are too long gets truncated. Command: `add CS2044 /name Data Structures and Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms Algorithms /tags Heavy, Math, Analysis`

![Module name can be too long.png](https://raw.githubusercontent.com/francisyzy/ped/master/files/0e5f0bce-a130-412c-b8b3-2531658be1c1.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: francisyzy/ped#1

**Comment by jedidiahC** [comment]
Side issue found in screenshot: Result Display Box way smaller than intended. (for our ref)

**Comment by jedidiahC** [comment]
Fixing text truncation issue considered as feature enhancement.
