### ISSUE TITLE
[PE-D][Tester A] Typo in Delete Video Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-F10-2/tp#252]
![image.png](https://raw.githubusercontent.com/Jiayan-Lim/ped/main/files/3653509d-e126-4b5a-bd41-8bb035f124f5.png)

Missing a space in between /lec and lecture 1

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Jiayan-Lim/ped#9

**Comment by shaowi** [comment]
Fixed it
