### ISSUE TITLE
[PE-D][Tester A] Typo in Find Modules or Lectures or Videos By Tag in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-F10-2/tp#259]
There is a typo found, shown in graph below:

![image.png](https://raw.githubusercontent.com/Jiayan-Lim/ped/main/files/e8a8ce12-fa7e-44a6-b343-27b148582d67.png)

should be `Week 1`

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Jiayan-Lim/ped#10

**Comment by shaowi** [comment]
Fixed it
