### ISSUE TITLE
[PE-D][Tester E] Undocumented features

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-F10-2/tp#261]
It appears that are are features like `import`, `export`, but that is not documented in the user guide.

![image.png](https://raw.githubusercontent.com/lhy-hoyin/ped/main/files/890c960f-e3ae-4613-9271-239f845073db.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: lhy-hoyin/ped#6

**Comment by hingen** [comment]
Noted. We will include it when we update the user guide.
