### ISSUE TITLE
[PE-D][Tester B] Unable to find when the name of lecture not in correct case

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-F10-2/tp#270]
![image.png](https://raw.githubusercontent.com/benedict733/ped/main/files/5f71f609-aa24-40ec-8593-bda827d867cc.png)

It can be quite common for someone to accidentally caps or lowercase and enter the name

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: benedict733/ped#5

**Comment by joytqt-1202** [comment]
Thanks for reporting this!
However, this is the intended design of the command.
Only the text between `find` and the first prefix is case insensitive, all other texts are case sensitive.
Will update user guide to better clarify this!
