### ISSUE TITLE
[PE-D][Tester E] Typo in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-F10-2/tp#271]
The following are spotted:

* Under "Find Videos in a Lecture By Tag",
mysterious backslash ending the line
![image.png](https://raw.githubusercontent.com/lhy-hoyin/ped/main/files/02864982-d3a5-4b3b-8cd6-dcca97d0f2c4.png)

* Under "Mark or Unmark Video", 
![image.png](https://raw.githubusercontent.com/lhy-hoyin/ped/main/files/b7351bcf-9912-42d5-a42f-1c8bf2b84ab0.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: lhy-hoyin/ped#8

**Comment by hingen** [comment]
Noted. These will be handled when cleaning up the user guide.
