### ISSUE TITLE
[PE-D][Tester E] No support for adding very long videos

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-F10-2/tp#284]
Does not support adding of videos >100 hours.

![image.png](https://raw.githubusercontent.com/lhy-hoyin/ped/main/files/f2d4439a-b5d0-4fd4-8006-c13cfae07aee.png)

It is possible that a very long video is released, and students are only expected to watch part of the video per week.

This limitation is also not indicated in the user guide.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: lhy-hoyin/ped#15

**Comment by hingen** [comment]
Interesting insight. If there was a long 100 hour video that the user is meant to watch part by part weekly, the user would have to be required to watch over 7.5 hours of content per week. Although this is not impossible, it seems unlikely to occur or might be extremely rare. As such we will consider this a "nice to have" and not a "functionality bug"

We will be updating the user guide to include this limitation.
